#![crate_name = "id"]
#![crate_type = "lib"]

pub mod config;
pub mod d_main;
pub mod def;
pub mod doom_data;
pub mod fixed;
pub mod game;
pub mod i_video;
pub mod id_sdl;
pub mod net;
pub mod p_setup;
pub mod r_bsp;
pub mod r_main;
pub mod r_state;
pub mod tables;
pub mod test_helper;
pub mod util;
pub mod v_patch;
pub mod v_video;
pub mod wad;
